# Generated by Django 4.1.5 on 2023-08-29 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicationreminder',
            name='status',
            field=models.IntegerField(choices=[(-1, 'Pending'), (1, 'Completed'), (0, 'Not Completed')]),
        ),
    ]
